name: Label Checker

on:
  pull_request:
    branches:
      - docs-staging
      - master

jobs:
  review-labels:
    name: Check for missing review label
    runs-on: ubuntu-latest

    steps:
      - id: prefix_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          one_of: "review:"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
  release-labels:
    name: Check for missing release label
    runs-on: ubuntu-latest

    steps:
      - id: prefix_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          one_of: "release:"
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  area-labels:
    name: Check for missing area label
    runs-on: ubuntu-latest

    steps:
      - id: prefix_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          one_of: "area:"
          repo_token: ${{ secrets.GITHUB_TOKEN }}