name: PR Checker

on:
  pull_request:
    branches:
      - docs-staging
      - master
    types: [opened, reopened, labeled]

jobs:

  initial-comment:
    name: PR Instructions
    runs-on: ubuntu-latest
    # if: github.event.action == 'opened'

    steps:
      - name: Add initial comment w/ instructions
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Initial comment
          message: |
            Initial message INSERT MESSAGE HERE using markdown
      - name: Checkout file
        uses: Bhacaz/checkout-files@v2
        with:
          files: ".github/pull_request_template.md"  
      - name: Description checker
        uses: jadrol/pr-description-checker-action@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          template-path: "./.github/pull_request_template.md"  
          comment: true
          comment-empty-description: "The PR description is empty, please add a valid description."
          comment-template-not-filled: "It looks like your description is too short. The PR description must be at least 85 characters. Missing **review** INSERT [MESSAGE](https://docs.zowe.org/) HERE using markdown
          1. Adding a second line to see what happens.
          2. Adding another line."

  review-labels:
    name: Check for missing review label
    runs-on: ubuntu-latest

    steps:
      - name: Review Label Check
        id: prefix_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          any_of: "needs review by"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Missing Review Label Comment PR
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Review label missing
          message: |
            Missing **review** INSERT [MESSAGE](https://docs.zowe.org/) HERE using markdown
            1. Adding a second line to see what happens.
            2. Adding another line.

          
  release-labels:
    name: Check for missing release label
    runs-on: ubuntu-latest

    steps:
      - id: prefix_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          one_of: "release:"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Missing Release Label Comment PR
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Release label missing
          message: |
            Missing release INSERT MESSAGE HERE using markdown

  area-labels:
    name: Check for missing area label
    runs-on: ubuntu-latest

    steps:
      - id: prefix_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          any_of: "area:"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Missing Area Label Comment PR
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Area label missing
          message: |
            Missing area INSERT MESSAGE HERE using markdown
    